<?php

class CT_CtIcon_Widget extends Case_Theme_Core_Widget_Base{
    protected $name = 'ct_icon';
    protected $title = 'Case Icons';
    protected $icon = 'eicon-alert';
    protected $categories = array( 'case-theme-core' );
    protected $params = '{"sections":[{"name":"section_icon","label":"Icons","tab":"content","controls":[{"name":"icons","label":"Icons","type":"repeater","controls":[{"name":"ct_icon","label":"Icon","type":"icons","fa4compatibility":"icon","default":{"value":"fas fa-star","library":"fa-solid"}},{"name":"icon_link","label":"Icon Link","type":"url","label_block":true}]},{"name":"style","label":"Style","type":"select","options":{"style1":"Style 1","style2":"Style 2","style3":"Style 3 (Box)"},"default":"style1"},{"name":"align","label":"Alignment","type":"choose","control_type":"responsive","options":{"left":{"title":"Left","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"right":{"title":"Right","icon":"eicon-text-align-right"},"justify":{"title":"Justified","icon":"eicon-text-align-justify"}},"selectors":{"{{WRAPPER}} .ct-icon1":"text-align: {{VALUE}};"}},{"name":"icon_color","label":"Icon Color","type":"color","selectors":{"{{WRAPPER}} .ct-icon1 a i":"color: {{VALUE}} !important;"}},{"name":"icon_color_hover","label":"Icon Color Hover","type":"color","selectors":{"{{WRAPPER}} .ct-icon1 a:hover i":"color: {{VALUE}} !important;"}},{"name":"box_icon_color","label":"Box Icon Color","type":"color","selectors":{"{{WRAPPER}} .ct-icon1 a i":"background-color: {{VALUE}} !important;"},"condition":{"style":"style3"}},{"name":"box_icon_color_hover","label":"Box Icon Color Hover","type":"color","selectors":{"{{WRAPPER}} .ct-icon1 a:hover i":"background-color: {{VALUE}} !important;"},"condition":{"style":"style3"}},{"name":"icon_font_size","label":"Icon Font Size","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .ct-icon1 a i":"font-size: {{SIZE}}{{UNIT}};"}},{"name":"icon_box_width","label":"Icon Box Width","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .ct-icon1.style3 a i":"width: {{SIZE}}{{UNIT}};"},"condition":{"style":"style3"}},{"name":"icon_box_height","label":"Icon Box Height","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .ct-icon1.style3 a i":"height: {{SIZE}}{{UNIT}};line-height: {{SIZE}}{{UNIT}};"},"condition":{"style":"style3"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}