<?php

class CT_CtProcess_Widget extends Case_Theme_Core_Widget_Base{
    protected $name = 'ct_process';
    protected $title = 'Case Process';
    protected $icon = 'eicon-sitemap';
    protected $categories = array( 'case-theme-core' );
    protected $params = '{"sections":[{"name":"section_content","label":"Process","tab":"content","controls":[{"name":"layout","label":"Layout","type":"select","options":{"1":"Layout 1","2":"Layout 2","3":"Layout 3","4":"Layout 4"},"default":"1"},{"name":"content_list","label":"Process","type":"repeater","controls":[{"name":"ct_icon","label":"Icon","type":"icons","fa4compatibility":"icon","default":{"value":"fas fa-star","library":"fa-solid"}},{"name":"title","label":"Title","type":"text","label_block":true},{"name":"description","label":"Description","type":"textarea","label_block":true},{"name":"btn_text","label":"Button Text","type":"text"},{"name":"btn_link","label":"Button Link","type":"url"}],"title_field":"{{{ title }}}"},{"name":"column","label":"Column","type":"select","options":{"1":"1","2":"2","3":"3","4":"4"},"default":"4"}]},{"name":"section_style","label":"Style","tab":"content","controls":[{"name":"line_image","label":"Line Image","type":"media","condition":{"layout":"1"}},{"name":"icon_color","label":"Icon Color","type":"color","selectors":{"{{WRAPPER}} .ct-process1.style2 .ct-process-icon":"color: {{VALUE}};"},"condition":{"layout":"2"}},{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .ct-process .ct-process-title":"color: {{VALUE}};"}},{"name":"title_typography","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .ct-process .ct-process-title"},{"name":"description_color","label":"Description Color","type":"color","selectors":{"{{WRAPPER}}  .ct-process .ct-process-description":"color: {{VALUE}};"}},{"name":"description_typography","label":"Description Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .ct-process .ct-process-description"},{"name":"box_bg_color","label":"Box Background Color","type":"color","selectors":{"{{WRAPPER}} .ct-process1.style2 .ct-piechart-process .ct-process-border::before":"background-color: {{VALUE}};"},"condition":{"layout":"2"}},{"name":"box_border_color","label":"Box Border Color","type":"color","selectors":{"{{WRAPPER}} .ct-process1.style2 .ct-piechart-process .ct-process-border::before":"border-color: {{VALUE}};"},"condition":{"layout":"2"}},{"name":"bar_color","label":"Bar Color","type":"color","condition":{"layout":["2","4"]}},{"name":"number_typography","label":"Number Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .ct-process .ct-process-number","condition":{"layout":["4"]}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'easy-pie-chart-lib-js','ct-piecharts-widget-js' );
}